#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
feature="$root/src/Affinities"
native_tree="$($root/scripts/ensure-valheim-source.sh)"

rg -Fq 'm_customData.Count' "$native_tree/Inventory.cs"
rg -Fq 'customDatum.Key' "$native_tree/Inventory.cs"
rg -Fq 'itemData.m_customData.Count' "$native_tree/ItemDrop.cs"
rg -Fq 'obj.m_customData = new Dictionary<string, string>(m_customData)' "$native_tree/ItemDrop.cs"
rg -Fq 'player.GetInventory().RemoveItem(m_craftUpgradeItem)' "$native_tree/InventoryGui.cs"
rg -Fq 'm_craftUpgradeItem.m_quality + 1' "$native_tree/InventoryGui.cs"

rg -Fq 'ReferenceEquals(item.m_dropPrefab, canonicalPrefab)' "$feature/AffinityState.cs"
rg -Fq 'item.m_quality,' "$feature/AffinityState.cs"
rg -Fq 'inventory.ContainsItem(target)' "$feature/AffinityApplication.cs"
rg -Fq 'return "affinity_already_installed"' "$feature/AffinityApplication.cs"
rg -Fq 'inventory.CountItems(resourceName)' "$feature/AffinityApplication.cs"
rg -Fq 'inventory.RemoveItem(resourceName, requirement.MaterialAmount)' "$feature/AffinityApplication.cs"
rg -Fq 'AffinityRules.CountConsumed(resourcesBefore, afterFailure)' "$feature/AffinityApplication.cs"
rg -Fq 'CheckUsable(player, false)' "$feature/AffinityApplication.cs"
rg -Fq 'NotifyInventoryChanged(inventory)' "$feature/AffinityApplication.cs"
rg -Fq 'item.m_customData[CustomDataKey] = value' "$feature/AffinityState.cs"
rg -Fq 'AffinityDiagnostics.Emit' "$feature/AffinityState.cs"
rg -Fq '[HarmonyPatch(typeof(Attack), "DoMeleeAttack")]' "$feature/AffinityPatches.cs"
rg -Fq '[HarmonyPrefix]' "$feature/AffinityPatches.cs"
rg -Fq 'ConditionalWeakTable<Attack, LungeSwingState>' "$feature/LungeRuntime.cs"
rg -Fq 'if (!AffinityState.IsLunge(weapon)) return;' "$feature/LungeRuntime.cs"
rg -Fq 'AffinityState.IsEligibleClub(state.Weapon)' "$feature/LungeRuntime.cs"
rg -Fq 'state.Consumed = true' "$feature/LungeRuntime.cs"
rg -Fq 'Swings.Remove(attack);' "$feature/LungeRuntime.cs"
rg -Fq 'Swings.Add(attack, new LungeSwingState(operationId, weapon!));' "$feature/LungeRuntime.cs"
rg -Fq 'ReferenceEquals(attack.GetWeapon(), state.Weapon)' "$feature/LungeRuntime.cs"
rg -Fq 'body.AddForce(impulse, ForceMode.VelocityChange)' "$feature/LungeRuntime.cs"
rg -Fq 'internal const float DefaultForce = 10f' "$feature/LungeRuntime.cs"
rg -Fq 'internal const float MinimumVerticalVelocity = 3f' "$feature/LungeRuntime.cs"
rg -Fq 'AffinityRules.RequiredVerticalImpulse(before.y, MinimumVerticalVelocity)' "$feature/LungeRuntime.cs"
rg -Fq 'yield return new WaitForFixedUpdate()' "$feature/LungeRuntime.cs"
rg -Fq 'body != null ? body.linearVelocity' "$feature/LungeRuntime.cs"
for field in velocity_before_x velocity_before_y velocity_before_z impulse_x impulse_y impulse_z velocity_after_x velocity_after_y velocity_after_z; do
  rg -Fq ".Number(\"$field\"" "$feature/LungeRuntime.cs"
done

for event in affinity_menu_discovered affinity_eligibility affinity_application_validation affinity_resources_consumed affinity_state_written affinity_state_loaded lunge_attempt_accepted lunge_attempt_rejected; do
  rg -Fq "\"$event\"" "$feature"
done

rg -Fq 'ui?.Active != true) return true' "$feature/AffinityForgeUiPatches.cs"
rg -Fq 'LeaveForNative();' "$feature/AffinityForgeUiPatches.cs"
rg -Fq 'new Button.ButtonClickedEvent()' "$feature/AffinityForgeUiNative.cs"
rg -Fq 'RemoveClonedGamepadBindings' "$feature/AffinityForgeUiNative.cs"
rg -Fq 'InputState.IsButtonDown' "$feature/AffinityForgeUi.cs"
rg -Fq 'gui.m_tabUpgrade.navigation = restoreUpgradeNavigation' "$feature/AffinityForgeUiNative.cs"
rg -Fq 'UnifiedPopup.Push(new YesNoPopup(' "$feature/AffinityForgeUi.cs"
rg -Fq '? $"{affinityName} Applied"' "$feature/AffinityForgeUi.cs"
rg -Fq '? $"This exact item already has {affinityName}."' "$feature/AffinityForgeUi.cs"
rg -Fq 'AffinityPresentation.BehaviorDescription(' "$feature/AffinityForgeUi.cs"
confirm_apply="$(sed -n '/internal void ConfirmApply()/,/private void CompleteApply/p' "$feature/AffinityForgeUi.cs")"
[[ "$confirm_apply" == *'if (AffinityRules.IsSameAffinity(AffinityState.Read(captured), selectedAffinity))'*'return;'*'UnifiedPopup.Push(new YesNoPopup('* ]]
rg -Fq 'requireForge: true' "$feature/AffinityForgeUi.cs"
rg -Fq 'consumeResources: true' "$feature/AffinityForgeUi.cs"
rg -Fq 'AffinityDebugCommand.TryExecute' "$root/src/EnemyTiers/BenheimTestCommandClient.cs"
rg -Fq 'AffinityState.StoredValue(weapon)' "$feature/AffinityDebugCommand.cs"
rg -Fq 'internal bool Replacing { get; }' "$feature/AffinityApplication.cs"
rg -Fq 'AffinityApplicationResult.Success(replacing)' "$feature/AffinityApplication.cs"
rg -Fq 'result.Replacing' "$feature/AffinityForgeUi.cs"
rg -Fq 'applied. The 1 Wood cost is nonrefundable.' "$feature/AffinityForgeUi.cs"
rg -Fq '[HarmonyPatch(' "$feature/AffinityInventoryTooltipPatch.cs"
rg -Fq 'typeof(InventoryGrid)' "$feature/AffinityInventoryTooltipPatch.cs"
rg -Fq '"CreateItemTooltip"' "$feature/AffinityInventoryTooltipPatch.cs"
rg -Fq 'AffinityState.Read(item)' "$feature/AffinityInventoryTooltipPatch.cs"
rg -Fq 'item.GetTooltip()' "$feature/AffinityInventoryTooltipPatch.cs"
rg -Fq 'LungeRuntime.Force' "$feature/AffinityInventoryTooltipPatch.cs"
rg -Fq '__instance.m_tooltipAnchor' "$feature/AffinityInventoryTooltipPatch.cs"
rg -Fq 'gui.m_minStationLevelIcon.sprite = station.m_icon' "$feature/AffinityForgeUi.cs"
rg -Fq 'gui.m_minStationLevelText.text = specification.StationLevel.ToString()' "$feature/AffinityForgeUi.cs"
rg -Fq 'gui.m_recipeRequirementList[0].transform' "$feature/AffinityForgeUi.cs"
rg -Fq 'restoreMinStationLevelSprite = gui.m_minStationLevelIcon.sprite' "$feature/AffinityForgeUiNative.cs"
rg -Fq 'gui.m_minStationLevelIcon.sprite = restoreMinStationLevelSprite' "$feature/AffinityForgeUi.cs"
rg -Fq 'ui?.Active != true) return true' "$feature/AffinityForgeUiPatches.cs"
rg -Fq 'AffinityForgeUi.Find(__instance)?.LeaveForNative()' "$feature/AffinityForgeUiPatches.cs"

rg -Fq 'AffinityState.AvailableFor(target) != selected' "$feature/AffinityApplication.cs"
rg -Fq 'CompleteApply(captured, selectedAffinity)' "$feature/AffinityForgeUi.cs"
rg -Fq 'bh debug affinity apply snipe' "$feature/AffinityDebugCommand.cs"

dotnet run --project "$root/tests/affinities/AffinitiesTests.csproj"
printf 'Affinity source, native seam, and rule checks passed\n'
