#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
event="$root/src/Infrastructure/DiagnosticEvent.cs"
diagnostics="$root/src/Infrastructure/Diagnostics.cs"
remote="$root/src/Infrastructure/RemoteDiagnostics.cs"
settings="$root/src/Infrastructure/DiagnosticsClientSettings.cs"
overlay="$root/src/Shortcuts/ShortcutOverlayConfig.cs"
plugin="$root/src/Plugin.cs"

grep -Fq 'new DiagnosticEventRoute(SelectEveryTypedEvent, RemoteDiagnostics.TryEnqueue)' "$diagnostics"
grep -Fq 'OptionalDestinations.Route(diagnosticEvent);' "$diagnostics"
test "$(grep -Fc 'RemoteDiagnostics.TryEnqueue' "$diagnostics")" -eq 1
grep -Fq 'internal string ToRemoteJsonLine(' "$event"
grep -Fq 'AppendJsonStringProperty(builder, "client_id", clientId);' "$event"
grep -Fq 'AppendJsonStringProperty(builder, "player_name", playerName);' "$event"
grep -Fq 'AppendJsonStringProperty(builder, "peer_id", peerId);' "$event"
grep -Fq 'AppendJsonStringProperty(builder, "session_id", session);' "$event"
grep -Fq 'AppendJsonStringProperty(builder, "mod_version", benheimVersion);' "$event"
grep -Fq 'AppendJsonStringProperty(builder, "build_id", buildId);' "$event"
grep -Fq 'internal const int RemoteSchema = 2;' "$event"
grep -Fq 'builder.Append(",\"fields\":{");' "$event"
grep -Fq 'if (field.Name != "operation_id")' "$event"
! grep -Fq 'RemoteFieldAllowed' "$event"
! grep -Fq 'RemoteInventoryFieldAllowed' "$event"
test "$(grep -Fc 'AppendJsonString(builder, field.Name);' "$event")" -eq 3

grep -Fq 'MaximumQueuedEvents = 512' "$remote"
grep -Fq 'MaximumBatchEvents = 100' "$remote"
grep -Fq 'MaximumEventCharacters = 16384' "$remote"
grep -Fq 'RequestTimeout = TimeSpan.FromSeconds(5)' "$remote"
grep -Fq 'queue.Clear();' "$remote"
grep -Fq 'toCancel?.Cancel();' "$remote"
grep -Fq 'Task.Run(() => Pump(cancellation.Token))' "$remote"
grep -Fq 'internal static string DeliveryStatus' "$remote"
grep -Fq 'sink.Enable();' "$remote"
grep -Fq 'BuildIdMatchesLoadedPlugin(buildId)' "$remote"
grep -Fq 'lastAcceptedUtc = DateTime.UtcNow;' "$remote"
grep -Fq 'RecordFailure($"HTTP {(int)response.StatusCode}");' "$remote"
grep -Fq 'PlayerName = playerName;' "$remote"
grep -Fq 'ZNet.GetUID().ToString(CultureInfo.InvariantCulture)' "$remote"
! grep -Eq 'LogOutput|Chat\.instance|GetHostName|GetPlayerID' "$remote"

! grep -Fq '"Share Diagnostics"' "$settings"
! grep -Fq 'SetShareDiagnostics' "$settings"
grep -Fq 'Guid.NewGuid().ToString("N")' "$settings"
grep -Fq '"Sharing Notice Shown"' "$settings"
grep -Fq '"DiagnosticsDeliveryStatus"' "$overlay"
grep -Fq 'RemoteDiagnostics.DeliveryStatus' "$overlay"
! grep -Fq '"Share Diagnostics"' "$overlay"
grep -Fq 'RemoteDiagnostics.Begin(Paths.ConfigPath);' "$plugin"
grep -Fq 'DiagnosticEvent.Create("Diagnostics", "delivery_probe")' "$plugin"
grep -Fq 'RemoteDiagnostics.Update();' "$plugin"
grep -Fq 'RemoteDiagnostics.Reset();' "$plugin"

dotnet run --project "$root/tests/diagnostics-sharing/DiagnosticsSharingTests.csproj"

echo "group typed diagnostics boundary checks passed"
