<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/GreydwarfResident/ResidentVisit.cs" Link="ResidentVisit.cs" />
    <Compile Include="../../src/GreydwarfResident/ResidentDrowsiness.cs" Link="ResidentDrowsiness.cs" />
    <Compile Include="../../src/GreydwarfResident/ResidentTubClient.cs" Link="ResidentTubClient.cs" />
  </ItemGroup>
</Project>
