<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/Inventory/QuickStackMessages.cs" Link="QuickStackMessages.cs" />
    <Compile Include="../../src/Inventory/QuickStackSummary.cs" Link="QuickStackSummary.cs" />
  </ItemGroup>
</Project>
