<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../shared/benheim-inventory-protocol/InventoryCapabilityModels.cs" Link="InventoryCapabilityModels.cs" />
  </ItemGroup>
</Project>
