<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>ValheimDevThrowing</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../ValheimDevRuntimeTests.csproj" />
  </ItemGroup>
</Project>
