#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=valheim-source-lib.sh
source "$script_dir/valheim-source-lib.sh"

command_name='diff-valheim-types'
fail() {
  printf '%s: %s\n' "$command_name" "$1" >&2
  exit 2
}

if [[ "$#" -eq 1 && "$1" == '--help' ]]; then
  cat <<'HELP'
Usage: diff-valheim-types.sh [--help] HASH-OR-PREFIX HASH-OR-PREFIX \
  [--type TYPE ... | TYPE ...]

Compare only the explicitly selected exact types in two complete cached
versions.  Each version is an exact 64-hex assembly SHA-256 or an
unambiguous non-empty lowercase/uppercase hex prefix.  Both versions must
exist under the current cache and have been generated by the current ILSpy
identity.  A normal diff exit status is returned: 0 means equal, 1 means a
selected type differs, and 2 means the request or cache is invalid.

Examples:
  diff-valheim-types.sh 0f3a... 9c41... --type Character --type Player
  diff-valheim-types.sh 0f3a 9c41 Character Player

This command intentionally has no whole-tree diff mode.
HELP
  exit 0
fi
if [[ "$#" -lt 3 ]]; then
  fail "usage: $0 [--help] HASH-OR-PREFIX HASH-OR-PREFIX [--type TYPE ... | TYPE ...]"
fi

left_selector="$1"
right_selector="$2"
shift 2

types=()
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --type)
      [[ "$#" -ge 2 ]] || fail "--type requires one exact type name"
      types+=("$2")
      shift 2
      ;;
    --type=*)
      [[ -n "${1#--type=}" ]] || fail "--type requires one exact type name"
      types+=("${1#--type=}")
      shift
      ;;
    --)
      shift
      while [[ "$#" -gt 0 ]]; do
        types+=("$1")
        shift
      done
      ;;
    -* )
      fail "unknown option '$1'; use --type or --help"
      ;;
    *)
      types+=("$1")
      shift
      ;;
  esac
done

if [[ "${#types[@]}" -eq 0 ]]; then
  fail "at least one explicit type is required; whole-tree diff is not supported"
fi

type_pattern='^[A-Za-z_][A-Za-z0-9_.+`]*$'
for requested_type in "${types[@]}"; do
  if [[ -z "$requested_type" || ! "$requested_type" =~ $type_pattern ]]; then
    fail "invalid type '$requested_type'; provide one exact Valheim type such as Character"
  fi
done
if ! command -v rg >/dev/null 2>&1; then
  fail "rg not found; install ripgrep or add rg to PATH"
fi

normalize_selector() {
  local selector="$1"
  if [[ -z "$selector" || ! "$selector" =~ ^[[:xdigit:]]{1,64}$ ]]; then
    fail "invalid assembly SHA-256 selector '$selector'; use 1-64 hexadecimal characters"
  fi
  printf '%s' "$selector" | tr '[:upper:]' '[:lower:]'
}

resolve_selector() {
  local selector="$1"
  local matches=()
  local candidate
  local candidate_name

  selector="$(normalize_selector "$selector")"
  for candidate in "$VALHEIM_SOURCE_CACHE_ROOT"/*; do
    [[ -d "$candidate" ]] || continue
    candidate_name="$(basename "$candidate")"
    [[ "$candidate_name" =~ ^[[:xdigit:]]{64}$ ]] || continue
    [[ "$candidate_name" == "$selector"* ]] || continue
    matches+=("$candidate_name")
  done

  if [[ "${#matches[@]}" -eq 0 ]]; then
    fail "assembly SHA selector '$selector' did not match a cached version"
  fi
  if [[ "${#matches[@]}" -ne 1 ]]; then
    fail "assembly SHA selector '$selector' is ambiguous; matches: ${matches[*]}"
  fi

  resolved_sha="${matches[0]}"
  resolved_tree="$VALHEIM_SOURCE_CACHE_ROOT/$resolved_sha/projects/$VALHEIM_SOURCE_ILSPY_ID"
  if ! valheim_source_tree_complete "$resolved_tree" "$resolved_sha" "$VALHEIM_SOURCE_ILSPY_ID"; then
    fail "cached version '$resolved_sha' is unavailable or incomplete for current decompiler $VALHEIM_SOURCE_ILSPY_ID: $resolved_tree"
  fi
}

# Resolve the current decompiler identity without requiring the currently
# installed game assembly: comparing two already-complete cached versions is a
# valid operation on a machine that only has the source cache and ilspycmd.
valheim_source_cache_root || fail "$VALHEIM_SOURCE_ERROR"
valheim_source_resolve_ilspy || fail "$VALHEIM_SOURCE_ERROR"
valheim_source_decompiler_identity || fail "$VALHEIM_SOURCE_ERROR"

resolve_selector "$left_selector"
left_sha="$resolved_sha"
left_tree="$resolved_tree"
resolve_selector "$right_selector"
right_sha="$resolved_sha"
right_tree="$resolved_tree"
if [[ "$left_sha" == "$right_sha" ]]; then
  fail "the two assembly SHA selectors resolve to the same cached version '$left_sha'"
fi

printf '%s: decompiler=%s\n' "$command_name" "$VALHEIM_SOURCE_ILSPY_ID" >&2
printf '%s: left=%s\n' "$command_name" "$left_sha" >&2
printf '%s: right=%s\n' "$command_name" "$right_sha" >&2

metadata_kind() {
  local metadata_file="$1"
  local requested_type="$2"
  local matches
  matches="$(awk -v requested="$requested_type" '
    $1 == "Class" || $1 == "Interface" || $1 == "Struct" ||
    $1 == "Delegate" || $1 == "Enum" {
      exact = $0
      sub(/^[^[:space:]]+[[:space:]]+/, "", exact)
      if (exact == requested) print $1
    }
  ' "$metadata_file")"
  if [[ -z "$matches" ]]; then
    return 1
  fi
  if [[ "$(printf '%s\n' "$matches" | wc -l | tr -d ' ')" -ne 1 ]]; then
    return 2
  fi
  printf '%s' "$matches"
}

source_for_type() {
  local tree_path="$1"
  local requested_type="$2"
  local kind="$3"
  local candidate
  local source_candidates=()
  local source_set=()
  local relative_name
  local nested_name
  local exact_relative_path
  local exact_nested_path
  local short_name
  local declaration
  local duplicate
  local existing

  short_name="${requested_type##*.}"
  declaration="$(printf '%s' "$kind" | tr '[:upper:]' '[:lower:]') $short_name"

  # ILSpy's nested-directory layout normally mirrors namespace and nested
  # type components.  A nested declaration may instead remain in its outer
  # type's file, so progressively remove trailing components.  We only accept
  # a candidate that contains the exact declaration and fail on ambiguity.
  relative_name="$(printf '%s' "$requested_type" | tr '.' '/')"
  nested_name="$(printf '%s' "$requested_type" | tr '.+' '//')"
  exact_relative_path="$tree_path/$relative_name.cs"
  exact_nested_path="$tree_path/$nested_name.cs"
  source_candidates=("$exact_relative_path" "$exact_nested_path")
  while [[ "$relative_name" == */* ]]; do
    relative_name="${relative_name%/*}"
    source_candidates+=("$tree_path/$relative_name.cs")
  done
  while [[ "$nested_name" == */* ]]; do
    nested_name="${nested_name%/*}"
    source_candidates+=("$tree_path/$nested_name.cs")
  done
  for candidate in "${source_candidates[@]}"; do
    [[ -f "$candidate" ]] || continue
    # Exact ILSpy project paths are authoritative after exact metadata
    # validation. Nested types can remain in an outer file, so only those
    # fallback candidates need a declaration check.
    if [[ "$candidate" == "$exact_relative_path" || "$candidate" == "$exact_nested_path" ]] ||
      rg -Fq --glob '*.cs' "$declaration" "$candidate"; then
      duplicate=0
      for existing in "${source_set[@]-}"; do
        [[ -n "$existing" && "$existing" == "$candidate" ]] && duplicate=1
      done
      (( duplicate == 0 )) && source_set+=("$candidate")
    fi
  done

  if [[ -z "${source_set[0]-}" ]]; then
    return 1
  fi
  if [[ "${#source_set[@]}" -ne 1 ]]; then
    printf '%s\n' "${source_set[@]}" >&2
    return 2
  fi
  printf '%s' "${source_set[0]}"
}

differences=0
for requested_type in "${types[@]}"; do
  left_kind=''
  right_kind=''
  if left_kind="$(metadata_kind "$left_tree/.benheim/types.txt" "$requested_type")"; then
    :
  else
    status=$?
    if [[ "$status" -eq 2 ]]; then
      fail "type '$requested_type' is ambiguous in left metadata"
    fi
    fail "type '$requested_type' is not present in left cached metadata"
  fi
  if right_kind="$(metadata_kind "$right_tree/.benheim/types.txt" "$requested_type")"; then
    :
  else
    status=$?
    if [[ "$status" -eq 2 ]]; then
      fail "type '$requested_type' is ambiguous in right metadata"
    fi
    fail "type '$requested_type' is not present in right cached metadata"
  fi
  if [[ "$left_kind" != "$right_kind" ]]; then
    fail "type '$requested_type' changed kind ($left_kind vs $right_kind); refusing ambiguous comparison"
  fi

  left_source=''
  right_source=''
  if left_source="$(source_for_type "$left_tree" "$requested_type" "$left_kind")"; then
    :
  else
    status=$?
    if [[ "$status" -eq 2 ]]; then
      fail "type '$requested_type' maps to multiple left source files"
    fi
    fail "could not map exact type '$requested_type' to a left source file"
  fi
  if right_source="$(source_for_type "$right_tree" "$requested_type" "$right_kind")"; then
    :
  else
    status=$?
    if [[ "$status" -eq 2 ]]; then
      fail "type '$requested_type' maps to multiple right source files"
    fi
    fail "could not map exact type '$requested_type' to a right source file"
  fi

  printf '%s: type=%s kind=%s\n' "$command_name" "$requested_type" "$left_kind" >&2
  if diff -u -L "$left_sha:$requested_type" "$left_source" \
    -L "$right_sha:$requested_type" "$right_source"; then
    :
  else
    status=$?
    if [[ "$status" -eq 1 ]]; then
      differences=1
    else
      fail "diff failed for exact type '$requested_type'"
    fi
  fi
done

exit "$differences"
