<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/Affinities/AffinityRules.cs" Link="AffinityRules.cs" />
    <Compile Include="../../src/Affinities/AffinityPresentation.cs" Link="AffinityPresentation.cs" />
  </ItemGroup>
</Project>
